export const AUTH_CLIENT = 'AUTH_CLIENT';
export const SET_LOGIN = 'SET_LOGIN';
export const SET_JS_CONFIG = 'SET_JS_CONFIG';
export const SET_PROGRESS = 'SET_PROGRESS';
export const SET_MEMBER_AVATARS = 'SET_MEMBER_AVATARS';

export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_RECORDS = 'SET_USER_RECORDS';
export const SET_TIP = 'SET_TIP';
export const SET_USER_LEVEL = 'SET_USER_LEVEL';
export const BUY_GOODS = 'BUY_GOODS';

export const SET_RANK = 'SET_RANK';
export const LIKE_FRIEND = 'LIKE_FRIEND';

export const SET_TASKS = 'SET_TASKS';
export const RESET_TASKS = 'RESET_TASKS';
export const CHANGE_NAVBAR = 'CHANGE_NAVBAR';

export const SET_TASK_QUANTITY_INFO = 'SET_TASK_QUANTITY_INFO';
export const SET_ACTIVE_TASK = 'SET_ACTIVE_TASK';
export const ADD_TASK_COMMENT = 'ADD_TASK_COMMENT';
export const SET_ACTIVE_TASK_COMMENTS = 'SET_ACTIVE_TASK_COMMENTS';
export const CLEAR_ACTIVE_TASK_COMMENTS = 'CLEAR_ACTIVE_TASK_COMMENTS';

export const SET_ACTIVE_ORDER = 'SET_ACTIVE_ORDER';
export const SET_ORDERS = 'SET_ORDERS';

export const FETCH_STH = 'FETCH_STH';

export const GOT_STH = 'GOT_STH';

export const SET_USER_CARDS = 'SET_USER_CARDS';
export const SET_USER_LOTTERY = 'SET_USER_LOTTERY';
export const SET_CARD_POOL = 'SET_CARD_POOL';
export const ADD_USER_LOTTERY = 'ADD_USER_LOTTERY';
export const ADD_USER_CARD = 'ADD_USER_CARD';
export const MINUS_USER_LOTTERY = 'MINUS_USER_LOTTERY';

export const SET_ACTIVR_NEWS = 'SET_ACTIVR_NEWS';
export const SET_NEWS = 'SET_NEWS';

export const SET_FREE_COURSES = 'SET_FREE_COURSES';
export const SET_ACTIVITIES = 'SET_ACTIVITIES';
export const RESET_ACTIVITIES = 'RESET_ACTIVITIES';
export const SET_ALL_GOODS = 'SET_ALL_GOODS';

export const OPEN_TASK_LOTTERY = 'OPEN_TASK_LOTTERY';

export const SET_NEW_STUDENT_TASKS = 'SET_NEW_STUDENT_TASKS';
export const SET_KEEP_INFO = 'SET_KEEP_INFO';
